### ISSUE TITLE
Non-JS Sources

### ISSUE THREAD

**Issue by bennypowers** [runem/web-component-analyzer#148]
Consider:
```html
<!-- index.html -->
<!-- head, etc... -->

    <define-element name="app-card">
      <template>
        <link rel="stylesheet" href="/app-card.css"/>
        <article>
          <header part="heading"><slot name="heading"></slot></header>
          <div id="content" part="content"><slot></slot></div>
          <footer part="actions"><slot name="actions"></slot></footer>
        </article>
      </template>
    </define-element>

```

```css
/* /app-card.css */
:host {
  display: flex;
  flex-flow: column nowrap;
  position: relative;
  background: white;
  box-shadow: var(--app-card-shadow);
  border: var(--app-card-border);
  border-radius: var(--app-card-border-radius);
}
```

It would be truly awesome if I could mark these up with comments in HTML source and have WCA spit out docs for them. That would really help future me when maintaining projects that use these kinds of quick css-only components.

-----

I get a tremendous amount of utility out of this project. Thank you very much for publishing and maintaining it.
